### ISSUE TITLE
when sharing on facebook

### ISSUE THREAD

**Issue by lindhard** [JohnnieLi/ng6-social-button#2]
If I share a specifik page e.g.:
https://miheroo.com/page/platforms-for-sustainable-development

The preview seems to take from the frontpage of the domain in this case https://miheroo.com

Is there are way to control the preview Facebook generates so its the actual page?

**Comment by JohnnieLi** [comment]
Hi,
Sorry to reply it late and thanks for your spelling fixed ! 
Actually it caused by Facebook's crawler. which like the most other social media crawlers, does not execute Javascript. Angular is client side application, For your link https://miheroo.com/page/platforms-for-sustainable-development, Facebook's crawler only treat it as [this - home index](https://developers.facebook.com/tools/debug/echo/?q=https%3A%2F%2Fmiheroo.com%2Fpage%2Fplatforms-for-sustainable-development)
  More Details click [here](https://developers.facebook.com/tools/debug/og/object/?q=https%3A%2F%2Fmiheroo.com%2Fpage%2Fplatforms-for-sustainable-development) 
So, You will need to use server-side rendering (in the form of [Angular universal](https://angular.io/guide/universal)) and/or prerendering _in combination with_ ng2-meta to provide your meta tags to these crawlers.
